export const message = {
  LOGIN_SUCCESS: 'Login Success!',
  NOT_FOUND_ACCOUNT: 'Cannot find the account!',
  NOT_FOUND_GROUP: 'Cannot find the group!',
  NOT_FOUND_ARTICLE: 'Cannot find the Article!',
  NOT_FOUND_CHAPTER: 'Cannot find the Chapter!',
  NOT_FOUND_COMMENT: 'Cannot find the Comment!',
  NOT_FOUND_USER: 'Cannot find the User!',
  NOT_FOUND_JOIN_REQUEST: 'Cannot find the join group request!',
  WRONG_ACCOUNT: 'Please provide correct account!',
  WAITING_FOR_APPROVE: 'Waiting for creator to approve',
  VERIFY_SUCCESS: 'Verify Success.',
  WRONG_CODE: 'Wrong Code!',
  INTERNAL_ERROR: 'Internal Error!',
  INVALID_INPUT: 'Invalid Input!',
  EMAIL_EXIST: 'Email has been used!',
  USERNAME_EXIST: 'Username has been used!',
  WRONG_EMAIL_FORMAT: 'The email format is wrong!',
  WRONG_PHONE_NBR_FORMAT: 'The phone number format is wrong!',
  PHONE_NBR_EXIST: 'Phone number has been used!',
  NAME_SHOULD_NOT_NULL: 'Name cannot be empty!',
  UPDATE_SUCCESS: 'Update Success!',
  UPDATE_FAIL: 'Update Fail!',
  CREATE_SUCCESS: 'Create Success!',
  CREATE_FAIL: 'Create Fail!',
  DELETE_FAIL: 'Delete Fail!',
  DELETE_SUCCESS: 'Delete Success!',
  SUCCESS: 'Success!',
  NO_PERMISSION: 'You have no permission for this request!',
};
